create table public.passenger
(
    id                 bigint generated by default as identity
        primary key,
    first_name         varchar(250) not null,
    last_name          varchar(250) not null,
    email              varchar(250) not null,
    rating             real      default 0.0,
    total_rating_count integer   default 0,
    inserted_at        timestamp default now()
);

insert into public.passenger
values (1, 'Иван', 'Иванов', 'iv.ivanov@gmail.com');


