spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO}
          private-key: ${SSH_KEY}
          search-paths: /{application}
          default-label: main
          passphrase: ${PASSPHRASE}
server:
  port: 8888