--liquibase formatted sql
--changeset Dmitry:1

create table passenger
(
    id         bigint generated by default as identity
        primary key,
    first_name varchar(250) not null,
    last_name  varchar(250) not null,
    email      varchar(250) not null,
    rating     real default 0.0
);


