apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server
  template:
    metadata:
      labels:
        app: cloud-config-server
    spec:
      containers:
        - name: cloud-config-server
          imagePullPolicy: Never
          image: cloud-config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: ssh-key
                  key: id_rsa
            - name: CONFIG_REPO
              valueFrom:
                secretKeyRef:
                  name: ssh-key
                  key: config_repo
          volumeMounts:
            - name: ssh-key-volume
              mountPath: /root/.ssh
              readOnly: true
      volumes:
        - name: ssh-key-volume
          secret:
            secretName: ssh-key
            items:
              - key: id_rsa
                path: id_rsa
                mode: 0600
              - key: known_hosts
                path: known_hosts