apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: cab
    spec:
      containers:
        - name: eureka-server
          imagePullPolicy: Never
          image: eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SERVICE_NAME
              value: "eureka-server"