apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
data:
  init.sql: |
    CREATE DATABASE keycloak_test;
    CREATE DATABASE booking;
    CREATE DATABASE driver;
    CREATE DATABASE account;
    CREATE DATABASE passenger;
  script.sh: |
    #!/bin/bash
    psql -U postgres -d account -c "CREATE EXTENSION IF NOT EXISTS pg_partman;"
---
