apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: change-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          imagePullPolicy: Never
          image: cab_db:latest
          securityContext:
            runAsUser: 999
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: init
              subPath: init.sql
            - mountPath: /docker-entrypoint-initdb.d/install_pg_partman.sh
              name: init
              subPath: script.sh
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: init
          configMap:
            name: init-script
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
        storageClassName: hostpath